window.PLAY_STORE_CONFIG = {
  panelWidth: 1080,
  panelHeight: 1920,
  panels: [
    {
      number: "01",
      kicker: "BETTERLECTIO TIL ANDROID",
      title: "Lectio.<br><em>Bare bedre.</em>",
      body: "Dit skema: hurtigt, roligt og faktisk til at finde rundt i.",
      image: "assets/schedule-da-light.png",
      device: { left: 294, top: 610, width: 760, rotate: -4.5 },
      accent: "blue",
    },
    {
      number: "02",
      kicker: "BESKEDER",
      title: "Beskeder.<br><em>Uden besvær.</em>",
      body: "Læs, svar og åbn bilag direkte i appen.",
      image: "assets/messages-da-light.png",
      device: { left: 1238, top: 584, width: 748, rotate: 3.8 },
      accent: "paper",
    },
    {
      number: "03",
      kicker: "LEKTIER",
      title: "Lektier.<br><em>Lige ved hånden.</em>",
      body: "Se materialer og dagens lektier, før timen starter.",
      image: "assets/homework-da-light.png",
      device: { left: 2388, top: 620, width: 750, rotate: -3.5 },
      accent: "blue",
    },
    {
      number: "04",
      kicker: "OPGAVER",
      title: "Alle deadlines.<br><em>Ét sted.</em>",
      body: "Afventer dig, afleveret eller mangler: du har overblikket.",
      image: "assets/assignments-da-light.png",
      device: { left: 3410, top: 595, width: 750, rotate: 3.2 },
      accent: "paper",
    },
    {
      number: "05",
      kicker: "KLASSEN",
      title: "Hele klassen.<br><em>Samlet.</em>",
      body: "Klassekammerater, skema og kontakt samlet ét sted.",
      image: "assets/student-da-light.png",
      device: { left: 4545, top: 610, width: 748, rotate: -3.6 },
      accent: "blue",
    },
    {
      number: "06",
      kicker: "MØRK TILSTAND",
      title: "Fravær.<br><em>Uden overraskelser.</em>",
      body: "Følg udviklingen fag for fag, også i mørk tilstand.",
      image: "assets/absence-da-dark.png",
      device: { left: 5600, top: 585, width: 760, rotate: 3.4 },
      accent: "night",
      repairDarkStatusBar: true,
    },
  ],
};
