devices([
    "iPhone 14 Pro Max"
])

languages([
  "da",
])

# The name of the scheme which contains the UI Tests
scheme("LPP-fastlane")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

erase_simulator(true)

stop_after_first_error(true)

# hvis man vil have en video med det, som går galt
#result_bundle(true)