window.PLAY_STORE_CONFIG = {
  panelWidth: 1080,
  panelHeight: 1920,
  panels: [
    {
      number: "01",
      kicker: "W4 ON ANDROID",
      title: "W4.<br><em>Now on mobile.</em>",
      body: "The W4 you already use — now as an app on your phone.",
      image: "assets/timetable-en-light.png",
      device: { left: 294, top: 610, width: 760, rotate: -4.5 },
      accent: "blue",
    },
    {
      number: "02",
      kicker: "STUDENTS",
      title: "Find anyone.<br><em>See their week.</em>",
      body: "Open a classmate and see their timetable, classes and house.",
      image: "assets/students-en-light.png",
      device: { left: 1238, top: 584, width: 748, rotate: 3.8 },
      accent: "paper",
    },
    {
      number: "03",
      kicker: "CLASSES",
      title: "Who's in the class.<br><em>Right there.</em>",
      body: "From a person or a lesson — the full roster in one tap.",
      image: "assets/classes-en-light.png",
      device: { left: 2388, top: 620, width: 750, rotate: -3.5 },
      accent: "blue",
    },
    {
      number: "04",
      kicker: "HOUSES",
      title: "Houses and rooms.<br><em>Everyone in them.</em>",
      body: "See who lives where, without the desktop lists.",
      image: "assets/houses-en-light.png",
      device: { left: 3410, top: 595, width: 750, rotate: 3.2 },
      accent: "paper",
    },
    {
      number: "05",
      kicker: "ASSESSMENTS",
      title: "What's due.<br><em>One calendar.</em>",
      body: "Month or list — W4's deadlines, without a second tab.",
      image: "assets/assessments-en-light.png",
      device: { left: 4545, top: 610, width: 748, rotate: -3.6 },
      accent: "blue",
    },
    {
      number: "06",
      kicker: "DARK MODE",
      title: "Absence.<br><em>No surprises.</em>",
      body: "Academics and EA, absences and lateness — also in dark mode.",
      image: "assets/absence-en-dark.png",
      device: { left: 5600, top: 585, width: 760, rotate: 3.4 },
      accent: "night",
    },
  ],
};
